# Generated by Django 5.1.3 on 2024-11-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnels', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(error_messages={'unique': 'Ordre Transport existe déjà'}, max_length=150, unique=True, verbose_name='Numero Ordre Transport ')),
                ('numero_fret', models.CharField(max_length=100, verbose_name='Numéro Fret ')),
                ('nature_colds', models.CharField(max_length=100, verbose_name='Nature Colds ')),
                ('quantite_transporte', models.CharField(max_length=150, verbose_name='Quantité transportée ')),
                ('numero_coli', models.CharField(max_length=150, verbose_name='N° Colis ')),
                ('numero_bc', models.CharField(max_length=100, verbose_name='N° BC ')),
                ('numero_bl', models.CharField(max_length=100, verbose_name='N° BL ')),
                ('transpQteTir', models.IntegerField(verbose_name='Transport Quantité ')),
                ('date_chargement_prevu', models.DateField(verbose_name='Date de chargement prévu ')),
                ('heure_debut', models.CharField(max_length=100, verbose_name='Heur début chargement ')),
                ('lieu_chargement', models.CharField(max_length=100, verbose_name='Lieu Chargement ')),
                ('heure_fin', models.CharField(max_length=100, verbose_name='Heure fin chargement ')),
                ('depart', models.CharField(max_length=100, verbose_name='Km Départ ')),
                ('kilometrage', models.CharField(max_length=100, verbose_name='Kilometrage prévu A/R ')),
                ('date_depart_prevu', models.DateField(verbose_name='Date de depart prevue ')),
                ('dure_mission', models.CharField(max_length=150, verbose_name='Estimation de durée de la mission ')),
                ('date_arive_site', models.DateTimeField(verbose_name='Date/heure arrivée site ')),
                ('date_livraison_site', models.DateTimeField(verbose_name='Date/heure livraison site ')),
                ('date_depart_site', models.DateTimeField(verbose_name='Date/heure départ site ')),
                ('date_sortie_parc', models.DateTimeField(verbose_name='Date/heure sortie parc ')),
                ('date_retour_parc', models.DateTimeField(verbose_name='Date/heure retour parc ')),
                ('etat_conformite_coli', models.TextField(verbose_name='Etat de conformité des colis livré ')),
                ('sanction', models.CharField(max_length=150, verbose_name='Sanction ')),
                ('slug', models.SlugField(unique=True)),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_chauffeur', to='personnels.personnel', verbose_name='Chauffeur ')),
                ('citerne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.citerne', verbose_name='Citerne ')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_client', to='personnels.personnel', verbose_name='Client ')),
                ('code_coli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.codecoli', verbose_name='Code type Colis ')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.destination', verbose_name='Destination ')),
                ('lieu_livraison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.lieulivraison', verbose_name='Lieu Livraison ')),
                ('nom_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_agent', to='personnels.personnel', verbose_name='Agent sécurité ')),
                ('nom_destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_destinataire', to='personnels.personnel', verbose_name='Destinaire ')),
                ('nom_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_responsable', to='personnels.personnel', verbose_name='Responsable transport ')),
                ('nom_superviseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_superviseur', to='personnels.personnel', verbose_name='Superviseur UMS sur site ')),
                ('seb_remorque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.sebremorque', verbose_name='Seb Remorque ')),
                ('seb_tracteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.sebtracteur', verbose_name='Seb Tracteur ')),
            ],
            options={
                'verbose_name': 'ordre_transport',
                'verbose_name_plural': 'ordre_transports',
                'db_table': 'ordre_transport',
            },
        ),
    ]
