# Generated by Django 5.1.3 on 2024-11-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_alter_personnel_type'),
        ('structures', '0001_initial'),
        ('traitements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordretransport',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_chauffeur', to='personnels.personnel', verbose_name='Chauffeur '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='citerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.citerne', verbose_name='Citerne '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_client', to='personnels.personnel', verbose_name='Client '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='code_coli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.codecoli', verbose_name='Code type Colis '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='date_arive_site',
            field=models.DateTimeField(blank=True, verbose_name='Date/heure arrivée site '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='date_chargement_prevu',
            field=models.DateField(blank=True, verbose_name='Date de chargement prévu '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='date_depart_prevu',
            field=models.DateField(blank=True, verbose_name='Date de depart prevue '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='date_depart_site',
            field=models.DateTimeField(blank=True, verbose_name='Date/heure départ site '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='date_livraison_site',
            field=models.DateTimeField(blank=True, verbose_name='Date/heure livraison site '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='date_retour_parc',
            field=models.DateTimeField(blank=True, verbose_name='Date/heure retour parc '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='date_sortie_parc',
            field=models.DateTimeField(blank=True, verbose_name='Date/heure sortie parc '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='depart',
            field=models.CharField(blank=True, max_length=100, verbose_name='Km Départ '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.destination', verbose_name='Destination '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='dure_mission',
            field=models.CharField(blank=True, max_length=150, verbose_name='Estimation de durée de la mission '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='etat_conformite_coli',
            field=models.TextField(blank=True, verbose_name='Etat de conformité des colis livré '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='heure_debut',
            field=models.CharField(blank=True, max_length=100, verbose_name='Heur début chargement '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='heure_fin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Heure fin chargement '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='kilometrage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kilometrage prévu A/R '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='lieu_chargement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu Chargement '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='lieu_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.lieulivraison', verbose_name='Lieu Livraison '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='nature_colds',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nature Colds '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='nom_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_agent', to='personnels.personnel', verbose_name='Agent sécurité '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='nom_destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_destinataire', to='personnels.personnel', verbose_name='Destinaire '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='nom_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_responsable', to='personnels.personnel', verbose_name='Responsable transport '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='nom_superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_transport_superviseur', to='personnels.personnel', verbose_name='Superviseur UMS sur site '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='numero',
            field=models.CharField(blank=True, error_messages={'unique': 'Ordre Transport existe déjà'}, max_length=150, unique=True, verbose_name='Numero Ordre Transport '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='numero_bc',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° BC '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='numero_bl',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° BL '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='numero_coli',
            field=models.CharField(blank=True, max_length=150, verbose_name='N° Colis '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='numero_fret',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro Fret '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='quantite_transporte',
            field=models.CharField(blank=True, max_length=150, verbose_name='Quantité transportée '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='sanction',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sanction '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='seb_remorque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.sebremorque', verbose_name='Seb Remorque '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='seb_tracteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.sebtracteur', verbose_name='Seb Tracteur '),
        ),
        migrations.AlterField(
            model_name='ordretransport',
            name='transpQteTir',
            field=models.IntegerField(blank=True, verbose_name='Transport Quantité '),
        ),
    ]
