# Generated by Django 5.1.3 on 2024-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitements', '0002_alter_ordretransport_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordretransport',
            name='date_chargement_prevu',
            field=models.DateField(blank=True, null=True, verbose_name='Date de chargement prévu '),
        ),
    ]
