# Generated by Django 5.1.3 on 2024-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10, verbose_name='Matricule ')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet ')),
                ('type', models.CharField(choices=[('CHAUFFEUR', 'CHAUFFEUR'), ('DESTINATAIRE', 'DESTINATAIRE'), ('SUPERVISEUR', 'SUPERVISEUR'), ('AGENT_SECURITE', 'AGENT SECURITE'), ('RESP_TRANSPORT', 'RESPONSABLE TRANSPORT'), ('CLIENT', 'CLIENT')], max_length=100, verbose_name='Type ')),
                ('fonction', models.CharField(blank=True, max_length=200, verbose_name='Fonction ')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse ')),
                ('telephone', models.CharField(max_length=9, verbose_name='Téléphone ')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'personnel',
                'verbose_name_plural': 'personnels',
                'db_table': 'personnel',
            },
        ),
    ]
