# Generated by Django 5.1.3 on 2024-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='type',
            field=models.CharField(choices=[('CHAUFFEUR', 'CHAUFFEUR'), ('RESP_TRANSPORT', 'RESPONSABLE TRANSPORT'), ('RESP_FLOTTE', 'RESPONSABLE fLOTTE'), ('CLIENT', 'CLIENT')], max_length=100, verbose_name='Type '),
        ),
    ]
